// Herkunft: MoinStudio src/preload/index.ts (MIT).
import { contextBridge, ipcRenderer, type IpcRendererEvent, webUtils } from 'electron'
import { IPC, isTabId, type CsApi, type JobAction, type ProfilDateiZweck, type TabId, type ToolId, type ToolProgressEvent, type UpdateStatus } from '@shared/app'
import type { Profil } from '@shared/profil'
import type { HardwareState } from '@shared/hardware'
import type { Sprache } from '@shared/i18n'
import type { QueueState } from '@shared/jobs'

/** Abonniert ein Ereignis aus dem Hauptprozess und liefert die Abmelde-Funktion. */
function ereignis<T>(kanal: string, handler: (wert: T) => void): () => void {
  const listener = (_e: IpcRendererEvent, wert: T): void => handler(wert)
  ipcRenderer.on(kanal, listener)
  return () => ipcRenderer.removeListener(kanal, listener)
}

const api = {
  appInfo: () => ipcRenderer.invoke(IPC.appInfo),
  onSelectTab(handler: (tab: TabId) => void) {
    return ereignis<unknown>(IPC.selectTab, (tab) => {
      if (isTabId(tab)) handler(tab)
    })
  },
  getAutostart: () => ipcRenderer.invoke(IPC.autostartGet),
  setAutostart: (enabled: boolean) => ipcRenderer.invoke(IPC.autostartSet, enabled === true),
  checkForUpdate: () => ipcRenderer.invoke(IPC.updateCheck),
  downloadUpdate: () => ipcRenderer.invoke(IPC.updateDownload),
  installUpdate: () => ipcRenderer.invoke(IPC.updateInstall),
  onUpdateStatus: (handler: (status: UpdateStatus) => void) => ereignis(IPC.updateStatus, handler),
  openLogs: () => ipcRenderer.invoke(IPC.openLogs),
  sprache: () => ipcRenderer.invoke(IPC.spracheGet),
  setzeSprache: (sprache: Sprache | null) => ipcRenderer.invoke(IPC.spracheSet, sprache),
  dataStatus: () => ipcRenderer.invoke(IPC.dataStatus),
  chooseDataDir: () => ipcRenderer.invoke(IPC.dataChoose),
  openDataDir: () => ipcRenderer.invoke(IPC.dataOpen),
  toolsStatus: () => ipcRenderer.invoke(IPC.toolsStatus),
  installTool: (id: ToolId) => ipcRenderer.invoke(IPC.toolsInstall, id),
  onToolProgress: (handler: (p: ToolProgressEvent) => void) => ereignis(IPC.toolsProgress, handler),
  hardwareState: () => ipcRenderer.invoke(IPC.hwState),
  runHardwareTest: () => ipcRenderer.invoke(IPC.hwRun),
  onHardwareState: (handler: (s: HardwareState) => void) => ereignis(IPC.hwState, handler),
  probeRender: () => ipcRenderer.invoke(IPC.hwProbe),
  jobsState: () => ipcRenderer.invoke(IPC.jobsState),
  jobAction: (action: JobAction, id?: string) => ipcRenderer.invoke(IPC.jobsAction, action, id),
  onJobsState: (handler: (s: QueueState) => void) => ereignis(IPC.jobsState, handler),
  jobImage: (id: string) => ipcRenderer.invoke(IPC.jobsImage, id),
  setupState: () => ipcRenderer.invoke(IPC.setupState),
  setupComplete: (done: boolean) => ipcRenderer.invoke(IPC.setupComplete, done),
  onSetupStep(handler: (step: number) => void) {
    return ereignis<unknown>(IPC.setupStep, (step) => {
      if (typeof step === 'number') handler(step)
    })
  },
  profilLaden: () => ipcRenderer.invoke(IPC.profilLaden),
  profilSpeichern: (profil: Profil) => ipcRenderer.invoke(IPC.profilSpeichern, profil),
  profilDateien: (zweck: ProfilDateiZweck, kontoId?: string) => ipcRenderer.invoke(IPC.profilDateien, zweck, kontoId),
  profilSkinName: (name: string) => ipcRenderer.invoke(IPC.profilSkinName, name),
  profilBild: (datei: string) => ipcRenderer.invoke(IPC.profilBild, datei),
  profilMetadaten: (kontoId: string) => ipcRenderer.invoke(IPC.profilMetadaten, kontoId),
  onProfilGeaendert: (handler: (profil: Profil) => void) => ereignis(IPC.profilGeaendert, handler),
  programmeFinden: () => ipcRenderer.invoke(IPC.programmeFinden),
  werkzeugeNoetig: () => ipcRenderer.invoke(IPC.werkzeugeNoetig),
  kiWege: () => ipcRenderer.invoke(IPC.kiWege),
  kiSchluessel: (id: string, schluessel: string | null) => ipcRenderer.invoke(IPC.kiSchluessel, id, schluessel),
  kiMonat: () => ipcRenderer.invoke(IPC.kiMonat),
  kiTest: (id: string) => ipcRenderer.invoke(IPC.kiTest, id),
  mcpZiele: () => ipcRenderer.invoke(IPC.mcpZiele),
  mcpVerbinden: (id: string) => ipcRenderer.invoke(IPC.mcpVerbinden, id),
  mcpEintrag: () => ipcRenderer.invoke(IPC.mcpEintrag),
  thumbStart: (start) => ipcRenderer.invoke(IPC.thumbStart, start),
  thumbDatei: (zweck) => ipcRenderer.invoke(IPC.thumbDatei, zweck),
  thumbAuftraege: () => ipcRenderer.invoke(IPC.thumbAuftraege),
  thumbErgebnis: (jobId) => ipcRenderer.invoke(IPC.thumbErgebnis, jobId),
  thumbAendern: (jobId, index, wunsch) => ipcRenderer.invoke(IPC.thumbAendern, jobId, index, wunsch),
  thumbLoeschen: (jobId) => ipcRenderer.invoke(IPC.thumbLoeschen, jobId),
  thumbExport: (jobId, index, format, typ) => ipcRenderer.invoke(IPC.thumbExport, jobId, index, format, typ),
  thumbKiStand: () => ipcRenderer.invoke(IPC.thumbKiStand),
  thumbVideo: (video, kontoId, titel) => ipcRenderer.invoke(IPC.thumbVideo, video, kontoId, titel),
  thumbVideoErgebnis: (jobId) => ipcRenderer.invoke(IPC.thumbVideoErgebnis, jobId),
  logoStart: (start) => ipcRenderer.invoke(IPC.logoStart, start),
  logoAendern: (jobId, index, wunsch) => ipcRenderer.invoke(IPC.logoAendern, jobId, index, wunsch),
  logoAuftraege: () => ipcRenderer.invoke(IPC.logoAuftraege),
  logoErgebnis: (jobId) => ipcRenderer.invoke(IPC.logoErgebnis, jobId),
  logoLoeschen: (jobId) => ipcRenderer.invoke(IPC.logoLoeschen, jobId),
  logoListe: () => ipcRenderer.invoke(IPC.logoListe),
  logoBild: (id) => ipcRenderer.invoke(IPC.logoBild, id),
  logoEintrag: (id, patch) => ipcRenderer.invoke(IPC.logoEintrag, id, patch),
  logoHochladen: (name, png) => ipcRenderer.invoke(IPC.logoHochladen, name, png),
  logoMerken: (jobId, index, name) => ipcRenderer.invoke(IPC.logoMerken, jobId, index, name),
  logoExport: (quelle, groesse) => ipcRenderer.invoke(IPC.logoExport, quelle, groesse),
  vorbildListe: (kontoId) => ipcRenderer.invoke(IPC.vorbildListe, kontoId),
  vorbildHinzu: (kontoId, quelle) => ipcRenderer.invoke(IPC.vorbildHinzu, kontoId, quelle),
  vorbildAendern: (kontoId, id, patch) => ipcRenderer.invoke(IPC.vorbildAendern, kontoId, id, patch),
  vorbildLoeschen: (kontoId, id) => ipcRenderer.invoke(IPC.vorbildLoeschen, kontoId, id),
  stilbuch: (kontoId) => ipcRenderer.invoke(IPC.stilbuch, kontoId),
  stilbuchErstellen: (kontoId) => ipcRenderer.invoke(IPC.stilbuchErstellen, kontoId),
  dateiPfad: (datei) => webUtils.getPathForFile(datei),
  schnittProjekte: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittProjekte, ...a),
  schnittImport: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittImport, ...a),
  schnittWellenform: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittWellenform, ...a),
  schnittLoeschen: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittLoeschen, ...a),
  schnittTranskript: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittTranskript, ...a),
  schnittTranskriptStart: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittTranskriptStart, ...a),
  schnittRohschnittStart: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittRohschnittStart, ...a),
  schnittListe: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittListe, ...a),
  schnittUmschalten: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittUmschalten, ...a),
  schnittBereich: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittBereich, ...a),
  schnittWunsch: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittWunsch, ...a),
  schnittEinstellungen: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittEinstellungen, ...a),
  schnittUmbenennen: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittUmbenennen, ...a),
  schnittBib: () => ipcRenderer.invoke(IPC.schnittBib),
  schnittBibSpeichern: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittBibSpeichern, ...a),
  schnittBibLoeschen: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittBibLoeschen, ...a),
  schnittBibDatei: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittBibDatei, ...a),
  schnittBibVorschau: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittBibVorschau, ...a),
  schnittBibPipette: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittBibPipette, ...a),
  schnittVorschau: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittVorschau, ...a),
  schnittExport: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittExport, ...a),
  schnittExportInfo: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittExportInfo, ...a),
  schnittExportSpeichern: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittExportSpeichern, ...a),
  schnittThumbnail: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittThumbnail, ...a),
  schnittHighlightsStart: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittHighlightsStart, ...a),
  schnittHighlights: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittHighlights, ...a),
  schnittClips: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittClips, ...a),
  schnittClipDateien: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittClipDateien, ...a),
  schnittClipOrdner: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittClipOrdner, ...a),
  schnittEffekte: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittEffekte, ...a),
  schnittEffektAendern: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittEffektAendern, ...a),
  schnittSpurHinzu: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittSpurHinzu, ...a),
  schnittSpurAendern: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittSpurAendern, ...a),
  planungKarten: (...a: unknown[]) => ipcRenderer.invoke(IPC.planungKarten, ...a),
  planungNeu: (...a: unknown[]) => ipcRenderer.invoke(IPC.planungNeu, ...a),
  planungAendern: (...a: unknown[]) => ipcRenderer.invoke(IPC.planungAendern, ...a),
  planungVerschieben: (...a: unknown[]) => ipcRenderer.invoke(IPC.planungVerschieben, ...a),
  planungLoeschen: (...a: unknown[]) => ipcRenderer.invoke(IPC.planungLoeschen, ...a),
  planungSchneiden: (...a: unknown[]) => ipcRenderer.invoke(IPC.planungSchneiden, ...a),
  planungThumbnail: (...a: unknown[]) => ipcRenderer.invoke(IPC.planungThumbnail, ...a),
  planungThumbVarianten: (...a: unknown[]) => ipcRenderer.invoke(IPC.planungThumbVarianten, ...a),
  planungThumbWaehlen: (...a: unknown[]) => ipcRenderer.invoke(IPC.planungThumbWaehlen, ...a),
  planungKi: (...a: unknown[]) => ipcRenderer.invoke(IPC.planungKi, ...a),
  planungKiStand: (...a: unknown[]) => ipcRenderer.invoke(IPC.planungKiStand, ...a),
  planungCrossPlan: (...a: unknown[]) => ipcRenderer.invoke(IPC.planungCrossPlan, ...a),
  planungPaket: (...a: unknown[]) => ipcRenderer.invoke(IPC.planungPaket, ...a),
  uploadVerbindungen: (...a: unknown[]) => ipcRenderer.invoke(IPC.uploadVerbindungen, ...a),
  uploadVerbinden: (...a: unknown[]) => ipcRenderer.invoke(IPC.uploadVerbinden, ...a),
  uploadTrennen: (...a: unknown[]) => ipcRenderer.invoke(IPC.uploadTrennen, ...a),
  uploadStart: (...a: unknown[]) => ipcRenderer.invoke(IPC.uploadStart, ...a),
  onPlanungGeaendert: (handler: () => void) => ereignis(IPC.planungGeaendert, handler),
  programmeStatus: (...a: unknown[]) => ipcRenderer.invoke(IPC.programmeStatus, ...a),
  programmSelbsttest: (...a: unknown[]) => ipcRenderer.invoke(IPC.programmSelbsttest, ...a),
  schnittProgramm: (...a: unknown[]) => ipcRenderer.invoke(IPC.schnittProgramm, ...a),
  leistungsbericht: () => ipcRenderer.invoke(IPC.hwLeistung),
  onLeistungStand: (handler: (s: { percent: number; step: string }) => void) => ereignis(IPC.hwLeistungStand, handler)
} as CsApi

contextBridge.exposeInMainWorld('cs', api)
